### PR TITLE
Added BONK script

### PR DESCRIPTION
**Pull request by KevOub**
Bonk script is a golang binary which monitors syscalls with the linux kernel audit module (created alongside SELinux) and logs it in an impactful way. If need be the script can kill malicious programs and also label IPs that are doing sketchy things. The source code is under bonk-bonk.zip/tar.gz

### CODE REVIEW

**Comment by KevOub** [comment]
Added our CCDC gameplan doc

**Comment by gb1035** [comment]
@KevOub Please add the original source for Bonk to this repo. Also, please add a little more info on what bonk is doing with each mode. The goal is for all teams to be able to use all resources. These corrections will need to be completed before Wed the 16th at 1:00pm CT.

**Review by gb1035 — CHANGES_REQUESTED** [review]
Needs work.

**Comment by KevOub** [comment]
Sorry about that. This time I uploaded all files not compressed in a zip file and have the README more prominent. Does this look better?

**Review by gb1035 — APPROVED** [review]
Thanks for this.

**Pull request merged**
